//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Cmd.proto
namespace Cmd
{
    [global::ProtoBuf.ProtoContract(Name=@"CLIENT_COMMAND")]
    public enum CLIENT_COMMAND
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"RQLoginGameServer", Value=100)]
      RQLoginGameServer = 100,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RQAccountOperation", Value=300)]
      RQAccountOperation = 300,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RQLoginGame", Value=400)]
      RQLoginGame = 400
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"SERVER_COMMAND")]
    public enum SERVER_COMMAND
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"RTLoginGameServer", Value=100)]
      RTLoginGameServer = 100,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RTAccountOperation", Value=300)]
      RTAccountOperation = 300,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RTLoginGame", Value=400)]
      RTLoginGame = 400
    }
  
}