//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Cmd.proto
namespace Cmd
{
    [global::ProtoBuf.ProtoContract(Name=@"CLIENT_COMMAND")]
    public enum CLIENT_COMMAND
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"RQGameServerInfo", Value=1)]
      RQGameServerInfo = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RQLogin", Value=2)]
      RQLogin = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"SERVER_COMMAND")]
    public enum SERVER_COMMAND
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"RTLogin", Value=0)]
      RTLogin = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RTGameServer", Value=1)]
      RTGameServer = 1
    }
  
}